AllCops:
  Excludes:
    - 'bin/*'

# Use UTF-8 as the source file encoding.
Encoding:
  Enabled: false

# Limit lines to 80 characters.
LineLength:
  Max: 120

# Avoid methods longer than 10 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

################################################################## DISABLED COPS
# These cops are disabled because we think they are a Bad Idea. If you add one
# here, make sure to add a comment describing what the cop does, and why this
# is a bad idea.

# Forces the argument names of the block given to #reduce to be `a, e`. Only
# applies on single-line blocks, but why would we want to force people to use
# less descriptive names?
ReduceArguments:
  Enabled: false

StringLiterals:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

Documentation:
  Enabled: false

FinalNewline:
  Enabled: false
